spring.application.name=online-loan-management
server.servlet.session.persistent=false

# DB properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable open session in view
spring.jpa.open-in-view=false

# JWT properties
spring.security.jwt.exp.time=${JWT_EXP_TIME:86400000}
spring.security.jwt.temp.exp.time=${JWT_TEMP_EXP_TIME:300000}
spring.security.jwt.secret.key=${JWT_SECRET}

# File upload
file.upload.directory=${FILE_UPLOAD_DIRECTORY:uploads/kyc-documents}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true